// const SchedColors = {
//     A: '#ffadad',
//     B: '#ffd6a5',
//     C: '#fdffb6',
//     D: '#c4ffbf',
//     E: '#9bf6ff',
//     F: '#a0c4ff',
//     G: '#bdb2ff',
//     WIN: '#ffc6ff',
//     Lion: '#ffd2ad',
//     Advisory: '#bfffe1',
// };

// const SchedColors = {
//     A: '#f9c6c9',
//     B: '#f7d9c4',
//     C: '#faedcb',
//     D: '#c9e4de',
//     E: '#c6e4f1',
//     F: '#c6cff1',
//     G: '#dbcdf0',
//     WIN: '#ffc6ff',
//     Lion: '#ffd2ad',
//     Advisory: '#bfffe1',
// };

const Colors = [
    '#ffffff',
    '#f9c6c9',
    '#f7d9c4',
    '#faedcb',
    '#c9e4da',
    '#c6e4f1',
    '#c6cff1',
    '#dbcdf0',
    '#ffc6ff',
    '#bfffe1',
    '#ffd2ad',
    '#f7facb',
    '#ffdeee',
    '#caede6',
    '#e5e1f7',
    '#fcf2e6',
    '#e3e3e3',
];

const InvertColors = [
    '#000000',
    '#6E1919',
    '#78421C',
    '#66520A',
    '#114D36',
    '#18526B',
    '#1A2B6B',
    '#3D1D6E',
    '#691C69',
    '#135435',
    '#663914',
    '#5F6319',
    '#61153A',
    '#06473A',
    '#241954',
    '#302921',
    '#292929',
];

const Schedule = [
    {
        dayName: 'Monday',
        blocks: [
            {
                block: 'A',
                number: 1,
                startTime: '9:00',
                endTime: '10:05',
                length: '65',
                lunch: [],
            },
            {
                block: 'Advisory',
                number: 1,
                startTime: '10:10',
                endTime: '10:30',
                length: '20',
                lunch: [],
            },
            {
                block: 'B',
                number: 1,
                startTime: '10:35',
                endTime: '11:40',
                length: '65',
                lunch: [],
            },
            {
                block: 'C',
                number: 1,
                startTime: '11:45',
                endTime: '13:25',
                length: '65',
                lunch: [
                    {
                        name: '1st',
                        startTime: '11:45',
                        endTime: '12:15',
                    },
                    {
                        name: '2nd',
                        startTime: '12:20',
                        endTime: '12:50',
                    },
                    {
                        name: '3rd',
                        startTime: '12:55',
                        endTime: '13:25',
                    },
                ],
            },
            {
                block: 'D',
                number: 1,
                startTime: '13:30',
                endTime: '14:35',
                length: '65',
                lunch: [],
            },
            {
                block: 'E',
                number: 1,
                startTime: '14:40',
                endTime: '15:45',
                length: '65',
                lunch: [],
            },
        ],
    },
    {
        dayName: 'Tuesday',
        blocks: [
            {
                block: 'A',
                number: 2,
                startTime: '9:00',
                endTime: '10:15',
                length: '75',
                lunch: [],
            },
            {
                block: 'B',
                number: 2,
                startTime: '10:20',
                endTime: '11:35',
                length: '75',
                lunch: [],
            },
            {
                block: 'F',
                number: 1,
                startTime: '11:40',
                endTime: '13:20',
                length: '65',
                lunch: [
                    {
                        name: '1st',
                        startTime: '11:40',
                        endTime: '12:10',
                    },
                    {
                        name: '2nd',
                        startTime: '12:15',
                        endTime: '12:45',
                    },
                    {
                        name: '3rd',
                        startTime: '12:50',
                        endTime: '13:20',
                    },
                ],
            },
            {
                block: 'G',
                number: 1,
                startTime: '13:25',
                endTime: '14:30',
                length: '65',
                lunch: [],
            },
            {
                block: 'Lion',
                number: 1,
                startTime: '14:35',
                endTime: '15:25',
                length: '50',
                lunch: [],
            },
        ],
    },
    {
        dayName: 'Wednesday',
        blocks: [
            {
                block: 'C',
                number: 2,
                startTime: '9:00',
                endTime: '10:15',
                length: '75',
                lunch: [],
            },
            {
                block: 'WIN',
                number: 1,
                startTime: '10:20',
                endTime: '11:10',
                length: '50',
                lunch: [],
            },
            {
                block: 'D',
                number: 2,
                startTime: '11:15',
                endTime: '13:05',
                length: '75',
                lunch: [
                    {
                        name: '1st',
                        startTime: '11:15',
                        endTime: '11:45',
                    },
                    {
                        name: '2nd',
                        startTime: '11:55',
                        endTime: '12:25',
                    },
                    {
                        name: '3rd',
                        startTime: '12:35',
                        endTime: '13:05',
                    },
                ],
            },
            {
                block: 'E',
                number: 2,
                startTime: '13:10',
                endTime: '14:25',
                length: '75',
                lunch: [],
            },
            {
                block: 'F',
                number: 2,
                startTime: '14:30',
                endTime: '15:45',
                length: '75',
                lunch: [],
            },
        ],
    },
    {
        dayName: 'Thursday',
        blocks: [
            {
                block: 'A',
                number: 3,
                startTime: '9:00',
                endTime: '10:15',
                length: '75',
                lunch: [],
            },
            {
                block: 'B',
                number: 3,
                startTime: '10:20',
                endTime: '11:35',
                length: '75',
                lunch: [],
            },
            {
                block: 'G',
                number: 2,
                startTime: '11:40',
                endTime: '13:30',
                length: '75',
                lunch: [
                    {
                        name: '1st',
                        startTime: '11:40',
                        endTime: '12:10',
                    },
                    {
                        name: '2nd',
                        startTime: '12:20',
                        endTime: '12:50',
                    },
                    {
                        name: '3rd',
                        startTime: '13:00',
                        endTime: '13:30',
                    },
                ],
            },
            {
                block: 'E',
                number: 3,
                startTime: '13:35',
                endTime: '14:50',
                length: '75',
                lunch: [],
            },
            {
                block: 'WIN',
                number: 2,
                startTime: '14:55',
                endTime: '15:45',
                length: '50',
                lunch: [],
            },
        ],
    },
    {
        dayName: 'Friday',
        blocks: [
            {
                block: 'C',
                number: 3,
                startTime: '9:00',
                endTime: '10:15',
                length: '75',
                lunch: [],
            },
            {
                block: 'WIN',
                number: 3,
                startTime: '10:20',
                endTime: '11:10',
                length: '50',
                lunch: [],
            },
            {
                block: 'D',
                number: 3,
                startTime: '11:15',
                endTime: '13:05',
                length: '75',
                lunch: [
                    {
                        name: '1st',
                        startTime: '11:15',
                        endTime: '11:45',
                    },
                    {
                        name: '2nd',
                        startTime: '11:55',
                        endTime: '12:25',
                    },
                    {
                        name: '3rd',
                        startTime: '12:35',
                        endTime: '13:05',
                    },
                ],
            },
            {
                block: 'F',
                number: 3,
                startTime: '13:10',
                endTime: '14:25',
                length: '75',
                lunch: [],
            },
            {
                block: 'G',
                number: 3,
                startTime: '14:30',
                endTime: '15:45',
                length: '75',
                lunch: [],
            },
        ],
    },
];
