const UserSettings = {
    title: 'NSHS Schedule',
    use24h: false,
    useColors: true,
    showTimes: true,
    showNumbers: true,
    north: false,
    affirmation: 'Semester 1',
};

const BlockSettings = {
    A1: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    A2: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    A3: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    B1: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    B2: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    B3: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    C1: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    C2: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    C3: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    D1: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    D2: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    D3: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    E1: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    E2: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    E3: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    F1: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    F2: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    F3: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    G1: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    G2: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    G3: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    Advisory: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    Lion: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
    WIN: {
        hasClass: true,
        class: '',
        room: '',
        teacher: '',
        lunch: 3,
        color: 0,
    },
};
